# Generated by Django 4.0.6 on 2022-07-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
