import Head from 'next/head'
import Menu from '../components/Menu'
import Nav from '../components/Nav'
import Gigs from '../components/Gigs'


export default function Home({gig_lists}) {
  return (
    <div className="m-2 font-bold">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="m-2 font-medium">
        <Nav/>
        <Menu/>
        <Gigs lists={gig_lists}/> 
      </main>
        
    </div>
  )
}

export async function getServerSideProps() {
  //   const { id } = context.query
  const res = await fetch("http://localhost:8000/products/");
  const data = await res.json();
  return {
    props: {
      gig_lists: data,
    },
  };
}